"""Update User table

Revision ID: 79514121bdba
Revises: 
Create Date: 2025-09-21 21:24:40.666404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79514121bdba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
